#!/bin/bash

# Build docker image
docker build -q=true -t creativecoding/neo4j-community github.com/creativecodingos/dokku-neo4j-dockerfiles.git
docker build -q=true -t creativecoding/neo4j-enterprise github.com/creativecodingos/dokku-neo4j-enterprise-dockerfiles.git

mkdir -p $DOKKU_ROOT/.neo4j
echo "include $DOKKU_ROOT/.neo4j/*/nginx.conf" > /etc/nginx/conf.d/dokku-neo4j-plugin.conf
