#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname "$0")/config"
source "$(dirname "$0")/functions"

if ! docker images | grep -e "^svendowideit/ambassador "; then
  docker pull svendowideit/ambassador:latest
fi

if ! docker images | grep -e "^dokkupaas/wait "; then
  docker pull dokkupaas/wait:latest
fi

mkdir -p "$NEO4J_PLUGIN_DATA_ROOT" || echo "Failed to create $NEO4J_PLUGIN_SERVICE directory"
chown dokku:dokku "$NEO4J_PLUGIN_DATA_ROOT"
